// Generated by CoffeeScript 2.5.1
(function() {
  var YAML, fs;

  fs = require('fs');

  YAML = require('yaml');

  exports.createManifest = function({name, src}) {
    var icon192, spec;
    icon192 = {
      src: '/icons/icon.192x192.png',
      sizes: '192x192',
      type: 'image/png'
    };
    spec = {
      name: name,
      short_name: name,
      description: 'Some description',
      start_url: '/',
      display: 'standalone',
      background_color: 'white',
      icons: [icon192]
    };
    return fs.writeFileSync(`${src}/manifest.yml`, YAML.stringify(spec));
  };

}).call(this);
