// Generated by CoffeeScript 2.5.1
(function() {
  var YAML, fs, icon;

  fs = require('fs');

  YAML = require('yaml');

  icon = function(size) {
    return {
      src: `/icons/${size}.png`,
      sizes: `${size}x${size}`,
      type: 'image/png'
    };
  };

  exports.createManifest = function({name, src}) {
    var spec;
    spec = {
      name: name,
      short_name: name,
      description: 'Some description',
      start_url: '/',
      display: 'standalone',
      background_color: 'white',
      icons: [icon(192), icon(512)]
    };
    return fs.writeFileSync(`${src}/manifest.yml`, YAML.stringify(spec));
  };

}).call(this);
