// Generated by CoffeeScript 2.5.1
(function() {
  var YAML, basename, build, buildManifest, buildPages, buildScripts, buildStyles, buildWorkers, copyFile, ensureDirExists, failIfDirNotExists, glob, handleWebpackErrors, pug, readFileSync, sass, webpack, writeFileSync;

  ({readFileSync, writeFileSync, copyFile} = require('fs'));

  ({basename} = require('path'));

  glob = require('glob');

  pug = require('pug');

  sass = require('sass');

  webpack = require('webpack');

  YAML = require('yaml');

  ({failIfDirNotExists, ensureDirExists} = require('./util'));

  build = function() {
    ensureDirExists(DIST);
    buildPages();
    buildStyles();
    buildScripts();
    buildWorkers();
    return buildManifest();
  };

  buildPages = function() {
    var dir, fn, i, j, len, names, results, source, sources;
    dir = `${SRC}/pages`;
    failIfDirNotExists(dir);
    sources = glob.sync(`${dir}/*.pug`);
    names = sources.map(function(file) {
      return basename(file, '.pug');
    });
    results = [];
    for (i = j = 0, len = sources.length; j < len; i = ++j) {
      source = sources[i];
      fn = pug.compile(readFileSync(source, 'utf-8'));
      results.push(writeFileSync(`${DIST}/${names[i]}.html`, fn()));
    }
    return results;
  };

  buildStyles = function() {
    var result, sourceDir, targetDir;
    sourceDir = `${SRC}/styles`;
    failIfDirNotExists(sourceDir);
    result = sass.renderSync({
      file: `${sourceDir}/main.sass`
    });
    targetDir = `${DIST}/styles`;
    ensureDirExists(targetDir);
    return writeFileSync(`${targetDir}/main.css`, result.css.toString());
  };

  handleWebpackErrors = function(error, stats) {
    var info;
    if (error) {
      console.error(error.stack || error);
      if (error.details) {
        console.error(error.details);
      }
      return;
    }
    info = stats.toJson();
    if (stats.hasErrors()) {
      console.error(info.errors);
    }
    if (stats.hasWarnings()) {
      return console.warn(info.warnings);
    }
  };

  buildScripts = function() {
    var conf, load_coffee, sourceDir, targetDir;
    sourceDir = `${SRC}/scripts`;
    failIfDirNotExists(sourceDir);
    targetDir = `${DIST}/scripts`;
    ensureDirExists(targetDir);
    load_coffee = {
      test: /\.coffee$/,
      use: 'coffee-loader'
    };
    conf = {
      mode: 'production',
      entry: `${sourceDir}/main.coffee`,
      output: {
        path: targetDir,
        filename: 'main.js'
      },
      module: {
        rules: [load_coffee]
      }
    };
    return webpack(conf, handleWebpackErrors);
  };

  buildWorkers = function() {
    var conf, load_coffee, sourceDir;
    sourceDir = `${SRC}/workers`;
    failIfDirNotExists(sourceDir);
    load_coffee = {
      test: /\.coffee$/,
      use: 'coffee-loader'
    };
    conf = {
      mode: 'production',
      entry: `${sourceDir}/sw.coffee`,
      output: {
        path: DIST,
        filename: 'sw.js'
      },
      module: {
        rules: [load_coffee]
      }
    };
    return webpack(conf, handleWebpackErrors);
  };

  buildManifest = function() {
    var json, manifest;
    ensureDirExists(`${DIST}/icons`);
    copyFile(`${SRC}/icons/icon.192x192.png`, `${DIST}/icons/icon.192x192.png`, function(error) {
      if (error) {
        throw error;
      }
    });
    manifest = YAML.parse(readFileSync(`${SRC}/manifest.yml`, 'utf-8'));
    json = JSON.stringify(manifest, null, 2);
    return writeFileSync(`${DIST}/manifest.webmanifest`, json);
  };

  module.exports = {build, buildPages, buildStyles, buildScripts, buildWorkers, buildManifest};

}).call(this);
