// Generated by CoffeeScript 2.5.1
(function() {
  var CWD, DIST, SRC, basename, buildPages, buildStyles, ensureDirExists, failIfDirNotExists, glob, pug, readFileSync, sass, writeFileSync;

  ({readFileSync, writeFileSync} = require('fs'));

  ({basename} = require('path'));

  glob = require('glob');

  pug = require('pug');

  sass = require('sass');

  ({failIfDirNotExists, ensureDirExists} = require('./util'));

  CWD = process.cwd();

  SRC = `${CWD}/src`;

  DIST = `${CWD}/dist`;

  exports.build = function() {
    ensureDirExists(DIST);
    buildPages();
    return buildStyles();
  };

  buildPages = function() {
    var dir, fn, i, j, len, names, results, source, sources;
    dir = `${SRC}/pages`;
    failIfDirNotExists(dir);
    sources = glob.sync(`${dir}/*.pug`);
    names = sources.map(function(file) {
      return basename(file, '.pug');
    });
    results = [];
    for (i = j = 0, len = sources.length; j < len; i = ++j) {
      source = sources[i];
      fn = pug.compile(readFileSync(source, 'utf-8'));
      results.push(writeFileSync(`${DIST}/${names[i]}.html`, fn()));
    }
    return results;
  };

  buildStyles = function() {
    var result, sourceDir, targetDir;
    sourceDir = `${SRC}/styles`;
    failIfDirNotExists(sourceDir);
    result = sass.renderSync({
      file: `${sourceDir}/main.sass`
    });
    targetDir = `${DIST}/styles`;
    ensureDirExists(targetDir);
    return writeFileSync(`${targetDir}/main.css`, result.css.toString());
  };

}).call(this);
