// Generated by CoffeeScript 2.5.1
(function() {
  var build, buildDeps, buildManifest, buildPages, buildScripts, buildStyles, buildWorkers, ensureDirExists;

  ({ensureDirExists} = require('./util'));

  ({buildDeps} = require('./build/js/deps'));

  ({buildScripts} = require('./build/js/scripts'));

  ({buildWorkers} = require('./build/js/workers'));

  ({buildPages} = require('./build/pages'));

  ({buildStyles} = require('./build/styles'));

  ({buildManifest} = require('./build/manifest'));

  build = async function() {
    ensureDirExists(DIST);
    await Promise.all([buildDeps(), buildScripts(), buildPages(), buildStyles(), buildManifest()]);
    return buildWorkers();
  };

  module.exports = {build, buildPages, buildStyles, buildDeps, buildScripts, buildWorkers, buildManifest};

}).call(this);
