// Generated by CoffeeScript 2.5.1
(function() {
  var build, printHelp, watch;

  ({build} = require('./build'));

  ({watch} = require('./watch'));

  exports.run = function() {
    var _agn, _node, command;
    [_node, _agn, command] = process.argv;
    switch (command) {
      case 'build':
        return build();
      case 'watch':
        return watch();
      default:
        return printHelp();
    }
  };

  printHelp = function() {
    return console.log('printHelp');
  };

}).call(this);
