// Generated by CoffeeScript 2.5.1
(function() {
  var build, create, printHelp, watch;

  global.VERSION = '0.0.5';

  global.CWD = process.cwd();

  global.SRC = `${CWD}/src`;

  global.DIST = `${CWD}/dist`;

  ({build} = require('./build'));

  ({watch} = require('./watch'));

  ({create} = require('./create'));

  exports.run = function() {
    var _agn, _node, command, name, template;
    [_node, _agn, command] = process.argv;
    switch (command) {
      case 'build':
        return build();
      case 'watch':
        return watch();
      case 'new':
        name = process.argv[3];
        template = process.argv[4];
        return create({name, template});
      case 'help':
        return printHelp();
      default:
        return printHelp();
    }
  };

  printHelp = function() {
    return console.log(`A tool for making PWAs.

  new NAME [TEMPLATE]    Create the directory named NAME and a new project inside of it.
  build                  Build the project inside of the dist directory.
  watch                  Watch for changes and rebuild the project continuously.
  help                   Show this message.`);
  };

}).call(this);
