// Generated by CoffeeScript 2.5.1
(function() {
  var build, create, printHelp, sw, version, watch;

  ({version} = require('../package.json'));

  global.VERSION = version;

  global.CWD = process.cwd();

  global.SRC = `${CWD}/src`;

  require('./ext');

  ({build} = require('./build'));

  ({watch} = require('./watch'));

  ({create} = require('./create'));

  ({sw} = require('./sw'));

  exports.run = function() {
    var _agn, _node, action, command, name, rest, template;
    [_node, _agn, command, ...rest] = process.argv;
    global.COMMAND = command;
    switch (command) {
      case 'build':
        global.DIST = `${CWD}/dist`;
        return build();
      case 'watch':
        global.DIST = `${CWD}/dist.dev`;
        return watch();
      case 'new':
        name = process.argv[3];
        template = process.argv[4];
        return create({name, template});
      case 'sw':
        action = rest[0];
        return sw(action);
      case 'help':
        return printHelp();
      default:
        return printHelp();
    }
  };

  printHelp = function() {
    return console.log(`A tool for making PWAs.

  new NAME [TEMPLATE]    Create the directory named NAME and a new project inside of it.
  build                  Build the project inside of the dist directory.
  watch                  Watch for changes and rebuild the project continuously.
  sw extract             Extract the default servide worker for modification.
  help                   Show this message.`);
  };

}).call(this);
