// Generated by CoffeeScript 2.5.1
(function() {
  var TEMPLATES, fs,
    indexOf = [].indexOf;

  fs = require('fs');

  TEMPLATES = ['bare'];

  exports.create = function({name, template}) {
    var createProject, dir;
    template || (template = 'bare');
    if (indexOf.call(TEMPLATES, template) >= 0) {
      ({createProject} = require(`./create/${template}`));
    } else {
      console.error(`No template named '${template}'. Available templates: ${TEMPLATES}`);
      process.exit(1);
    }
    dir = `${CWD}/${name}`;
    if (fs.existsSync(dir)) {
      console.error(`${dir} already exists.`);
      process.exit(1);
    } else {
      console.log(`Creating a new project inside of ${dir}`);
      fs.mkdirSync(dir);
    }
    return createProject({name, dir});
  };

}).call(this);
