// Generated by CoffeeScript 2.5.1
(function() {
  var printHelp;

  exports.sw = function(action) {
    switch (action) {
      case 'extract':
        return console.log('Extracting the default SW');
      default:
        console.error(`Unknown action: ${action}`);
        return printHelp();
    }
  };

  printHelp = function() {
    return console.log(`makepwa sw ACTION
The actions related to service workers.

ACTIONS:
  extract             Extract the default servide worker for modification.`);
  };

}).call(this);
