// Generated by CoffeeScript 2.5.1
(function() {
  var ensureDirExists, printHelp;

  ({ensureDirExists} = require('./util'));

  exports.sw = function(action) {
    var registrationScript, serviceWorker;
    switch (action) {
      case 'extract':
        ensureDirExists(`${SRC}/scripts`);
        ensureDirExists(`${SRC}/workers`);
        registrationScript = `${SRC}/scripts/register_sw.coffee`;
        serviceWorker = `${SRC}/workers/sw.coffee`;
        IO.copy('/tmp/makepwa/register_sw.coffee', registrationScript);
        IO.copy('/tmp/makepwa/sw.coffee', serviceWorker);
        return console.log(`Extracted the default service worker and its registration script. You can modify them now at:
${registrationScript}
${serviceWorker}`);
      default:
        console.error(`Unknown action: ${action}`);
        return printHelp();
    }
  };

  printHelp = function() {
    return console.log(`makepwa sw ACTION
The actions related to service workers.

ACTIONS:
  extract             Extract the default servide worker for modification.`);
  };

}).call(this);
