// Generated by CoffeeScript 2.5.1
(function() {
  var fs;

  fs = require('fs');

  exports.ensureDirExists = function(dir) {
    if (!fs.existsSync(dir)) {
      return fs.mkdirSync(dir);
    }
  };

  exports.failIfDirNotExists = function(dir) {
    if (!fs.existsSync(dir)) {
      console.log(`${dir} does not exist.`);
      return process.exit(1);
    }
  };

}).call(this);
