// Generated by CoffeeScript 2.5.1
(function() {
  var fs;

  fs = require('fs');

  exports.ensureDirExists = function(dir) {
    if (!fs.existsSync(dir)) {
      return fs.mkdirSync(dir);
    }
  };

}).call(this);
