// Generated by CoffeeScript 2.5.1
(function() {
  var chokidar;

  chokidar = require('chokidar');

  exports.watch = function() {
    console.log(chokidar);
    return console.log('from watch');
  };

}).call(this);
