// Generated by CoffeeScript 2.5.1
(function() {
  var build, buildManifest, buildPages, buildScripts, buildStyles, buildWorkers, chokidar, watching;

  chokidar = require('chokidar');

  ({build, buildPages, buildStyles, buildScripts, buildWorkers, buildManifest} = require('./build'));

  exports.watch = function() {
    build();
    watching(['src/pages/*.pug'], buildPages);
    watching(['src/styles/*.sass'], buildStyles);
    watching(['src/scripts/**/*.coffee', 'src/scripts/**/*.js'], buildScripts);
    watching(['src/workers/**/*.coffee', 'src/scripts/**/*.js'], buildWorkers);
    return watching(['src/manifest.yml'], buildManifest);
  };

  watching = function(array, fn) {
    var watcher;
    watcher = chokidar.watch(array, {
      persistent: true,
      ignoreInitial: true
    });
    return watcher.on('all', function(event, path) {
      console.log(event, path);
      return fn();
    });
  };

}).call(this);
