// Generated by CoffeeScript 2.5.1
(function() {
  var BS, build, buildDeps, buildManifest, buildPages, buildScripts, buildStyles, buildWorkers, chokidar, watching;

  chokidar = require('chokidar');

  BS = require('browser-sync');

  ({build, buildPages, buildStyles, buildDeps, buildScripts, buildWorkers, buildManifest} = require('./build'));

  exports.watch = function() {
    var bs;
    build();
    watching(['src/pages/*.pug'], buildPages);
    watching(['src/styles/*.sass'], buildStyles);
    watching(['src/deps.yml'], buildDeps);
    watching(['src/scripts/**/*.coffee', 'src/scripts/**/*.js'], buildScripts);
    watching(['src/workers/**/*.coffee', 'src/scripts/**/*.js'], buildWorkers);
    watching(['src/manifest.yml'], buildManifest);
    bs = BS.create();
    return bs.init({
      server: DIST,
      files: `${DIST}/**/*`,
      open: false,
      ui: false,
      notify: false
    });
  };

  watching = function(array, fn) {
    var watcher;
    watcher = chokidar.watch(array, {
      persistent: true,
      ignoreInitial: true
    });
    return watcher.on('all', function(event, path) {
      console.log(event, path);
      return fn();
    });
  };

}).call(this);
