// Generated by CoffeeScript 2.5.1
(function() {
  var copyFile, readFile, rename, writeFile;

  ({readFile, writeFile, copyFile, rename} = require('fs').promises);

  global.IO = {
    read: function(path) {
      return readFile(path, 'utf-8');
    },
    write: writeFile,
    copy: copyFile,
    move: rename
  };

}).call(this);
